name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Copy build dependencies
      run: ./copy-build-deps.sh
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag marcmarina/turbo-playground
