name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
    - name: Install dependencies
      run: yarn install
    - name: Test
      run: yarn test
    - name: Copy build dependencies
      run: ./copy-build-deps.sh
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag marcmarina/turbo-playground